/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Module, Capability, PlanId } from '../types';

export const MOCK_MODULES: Module[] = [
  {
    id: "m5",
    publicName: "RIME",
    glyph: "λ.rim",
    internalName: "RIME",
    nanoEssence: "rime-core-clarity",
    description: "Clarification du raisonnement, séparation faits/hypothèses et moteur anti-hallucination.",
    category: "reasoning",
    tier: PlanId.FREE,
    compatibleOutputs: ["DIRECT_PROMPT"],
    dependencies: [],
    conflicts: [],
    tokenCostWeight: 120,
    tags: ["reliability", "ambiguity-reduction"],
    rarity: "LEGENDARY",
    marketValue: 7500
  },
  {
    id: "m22",
    publicName: "PRIMORDIA",
    glyph: "π.pri",
    internalName: "PRIMORDIA",
    nanoEssence: "primordia-truth-gate",
    description: "Veto vérité, cohérence, sécurité et gestion d'incertitude. Noyau originel.",
    category: "governance",
    tier: PlanId.FREE,
    compatibleOutputs: ["DIRECT_PROMPT", "MASTER_PREFS"],
    dependencies: [],
    conflicts: [],
    tokenCostWeight: 1000,
    tags: ["strong-governance"],
    rarity: "MYTHIC",
    marketValue: 45000
  },
  {
    id: "m3",
    publicName: "ECOTWIN",
    glyph: "ε.eco",
    internalName: "ECOTWIN",
    nanoEssence: "ecotwin-token-sobriety",
    description: "Sobriété cognitive, réduction surcharge et efficience énergétique.",
    category: "efficiency",
    tier: PlanId.FREE,
    compatibleOutputs: ["DIRECT_PROMPT"],
    dependencies: [],
    conflicts: [],
    tokenCostWeight: 50,
    tags: ["reliability"],
    rarity: "EPIC",
    marketValue: 1200
  },
  {
    id: "m26",
    publicName: "CREA120",
    glyph: "χ.cre",
    internalName: "CREA120",
    nanoEssence: "crea120-controlled-divergence",
    description: "Créativité contrôlée sous contraintes sémantiques.",
    category: "creation",
    tier: PlanId.CREATOR,
    compatibleOutputs: ["DIRECT_PROMPT"],
    dependencies: [],
    conflicts: [],
    tokenCostWeight: 200,
    tags: ["guided-creativity"],
    rarity: "RARE",
    marketValue: 1500
  },
  {
    id: "m25",
    publicName: "AURA_MXB",
    glyph: "α.aur",
    internalName: "AURA_MXB",
    nanoEssence: "aura-mxb-decision-scorecard",
    description: "Arbitrage impact, risque et marge de sécurité décisionnelle.",
    category: "strategy",
    tier: PlanId.CREATOR,
    compatibleOutputs: ["DIRECT_PROMPT", "MASTER_PREFS"],
    dependencies: ["m5"],
    conflicts: [],
    tokenCostWeight: 350,
    tags: ["consultant-mode", "sme-mode"],
    rarity: "EPIC",
    marketValue: 3500
  },
  {
    id: "m4",
    publicName: "GPL",
    glyph: "γ.gpl",
    internalName: "GPL",
    nanoEssence: "gpl-exec-contract",
    description: "Contrat d’exécution GrenapromptLinked transformant la demande humaine en structure auditable.",
    category: "protocol",
    tier: PlanId.FREE,
    compatibleOutputs: ["PROJECT_MD", "MASTER_PREFS"],
    dependencies: [],
    conflicts: [],
    tokenCostWeight: 200,
    tags: ["ambiguity-reduction", "professional-structure", "project-export", "sme-mode"],
    rarity: "EXOTIC",
    marketValue: 5000
  },
  {
    id: "m14",
    publicName: "ARCH_PLUS",
    glyph: "ø.arc",
    internalName: "ARCH_PLUS",
    nanoEssence: "arch-plus-profile-frame",
    description: "Architecture de profil : personae, rôles, limites et cadres d'action.",
    category: "architecture",
    tier: PlanId.PRO,
    compatibleOutputs: ["DIRECT_PROMPT", "PROJECT_MD"],
    dependencies: [],
    conflicts: [],
    tokenCostWeight: 250,
    tags: ["professional-structure"],
    rarity: "EPIC",
    marketValue: 2200
  },
  {
    id: "m27",
    publicName: "VG_PLUS",
    glyph: "ν.vgp",
    internalName: "VG_PLUS",
    nanoEssence: "vg-plus-visual-layers",
    description: "VG+ : Pipeline visuel structurel (manga, storyboard, vidéo).",
    category: "visual",
    tier: PlanId.PRO,
    compatibleOutputs: ["PROJECT_MD"],
    dependencies: [],
    conflicts: [],
    tokenCostWeight: 300,
    tags: ["visual-pipeline"],
    rarity: "RARE",
    marketValue: 2200
  },
  {
    id: "m28",
    publicName: "SONCAS",
    glyph: "σ.son",
    internalName: "SONCAS",
    nanoEssence: "soncas-business-tuning",
    description: "Adaptation business et commerciale par leviers comportementaux.",
    category: "business",
    tier: PlanId.CREATOR,
    compatibleOutputs: ["DIRECT_PROMPT"],
    dependencies: [],
    conflicts: [],
    tokenCostWeight: 100,
    tags: ["sme-mode"],
    rarity: "COMMON",
    marketValue: 500
  },
  {
    id: "m13",
    publicName: "ORA_COMPILER_CORE",
    glyph: "ω.com",
    internalName: "ORA_COMPILER_CORE",
    nanoEssence: "ora-compiler-artifact-frame",
    description: "Compilation et export d’artefacts projet exploitables.",
    category: "compiler",
    tier: PlanId.FREE,
    compatibleOutputs: ["DIRECT_PROMPT", "PROJECT_MD", "MASTER_PREFS"],
    dependencies: [],
    conflicts: [],
    tokenCostWeight: 500,
    tags: ["project-export"],
    rarity: "LEGENDARY",
    marketValue: 12000
  },
  {
    id: "m6",
    publicName: "HALO_TRACECORE",
    glyph: "τ.hal",
    internalName: "HALO_TRACECORE",
    nanoEssence: "halo-tracecore-ledger",
    description: "Audit hashable, trace des essences, verdicts et incertitudes.",
    category: "governance",
    tier: PlanId.FREE,
    compatibleOutputs: ["PROJECT_MD", "MASTER_PREFS"],
    dependencies: [],
    conflicts: [],
    tokenCostWeight: 250,
    tags: ["governance-audit"],
    rarity: "MYTHIC",
    marketValue: 25000
  },
  {
    id: "m29",
    publicName: "ESSENCE_ME_BACKEND",
    glyph: "μ.me",
    internalName: "ESSENCE_ME_BACKEND",
    nanoEssence: "essence-me-decision-compression",
    description: "Couper les boucles d’incertitude et forcer l'action minimale utile.",
    category: "efficiency",
    tier: PlanId.FREE,
    compatibleOutputs: ["DIRECT_PROMPT"],
    dependencies: ["m5", "m22", "m3"],
    conflicts: [],
    tokenCostWeight: 150,
    tags: ["anti-loop", "compression", "uncertainty", "decision", "compute", "decision-compression"],
    rarity: "EPIC",
    marketValue: 3000
  },
  {
    id: "m23",
    publicName: "H-NERONS Runtime Pack",
    glyph: "η.ner",
    internalName: "MODULE_H_NERONS_V1_0",
    nanoEssence: "η.ner",
    description: "Qualification factuelle pré-émission avec trace GL/GL_G. Pack de gouvernance runtime.",
    category: "governance",
    tier: PlanId.FREE,
    compatibleOutputs: ["DIRECT_PROMPT"],
    dependencies: [],
    conflicts: [],
    tokenCostWeight: 350,
    tags: ["runtime-governance-module"],
    rarity: "EXOTIC",
    marketValue: 2500
  }
];

export const MOCK_CAPABILITIES: Capability[] = [
  {
    id: "cap_foundation",
    label: "ORA Core Foundation",
    description: "Socle de base ORA : RIME, PRIMORDIA, ECOTWIN, GPL, ORA_COMPILER, HALO. (Pack obligatoire injecté)",
    category: "Core",
    mappedModules: ["m5", "m22", "m3", "m4", "m13", "m6"],
    requiredPlan: PlanId.FREE,
    keywords: ["foundation", "core", "base", "logic", "truth", "audit"]
  },
  {
    id: "reliability",
    label: "Reliability",
    description: "Assure la fiabilité et la précision du flux sémantique via RIME et ECOTWIN.",
    category: "Core",
    mappedModules: ["m5", "m3"],
    requiredPlan: PlanId.FREE,
    keywords: ["reliability", "precision", "rime", "ecotwin"]
  },
  {
    id: "ambiguity-reduction",
    label: "Ambiguity Reduction",
    description: "Réduit les ambiguïtés et clarifie le raisonnement en séparant faits et hypothèses.",
    category: "Core",
    mappedModules: ["m5", "m4"],
    requiredPlan: PlanId.FREE,
    keywords: ["clarity", "ambiguity", "rime", "gpl"]
  },
  {
    id: "guided-creativity",
    label: "Guided Creativity",
    description: "Créativité contrôlée sous contraintes sémantiques strictes.",
    category: "Exotic",
    mappedModules: ["m26"],
    requiredPlan: PlanId.CREATOR,
    keywords: ["creative", "crea120"]
  },
  {
    id: "professional-structure",
    label: "Professional Structure",
    description: "Architecture de profil et structuration professionnelle pour experts.",
    category: "Integration",
    mappedModules: ["m4", "m14"],
    requiredPlan: PlanId.PRO,
    keywords: ["structure", "gpl", "arch-plus"]
  },
  {
    id: "strong-governance",
    label: "Strong Governance",
    description: "Veto de vérité absolue et contrôle de sécurité PRIMORDIA.",
    category: "Core",
    mappedModules: ["m22"],
    requiredPlan: PlanId.FREE,
    keywords: ["governance", "primordia", "truth"]
  },
  {
    id: "project-export",
    label: "Project Export",
    description: "Compilation et export complet des artefacts projet (GPL + Compiler).",
    category: "Core",
    mappedModules: ["m4", "m13"],
    requiredPlan: PlanId.FREE,
    keywords: ["export", "compiler", "gpl"]
  },
  {
    id: "consultant-mode",
    label: "Consultant Mode",
    description: "Analyse stratégique et arbitrage d'impact via Aura MxB.",
    category: "Reinforcement",
    mappedModules: ["m25"],
    requiredPlan: PlanId.CREATOR,
    keywords: ["consultant", "strategy", "aura-mxb"]
  },
  {
    id: "sme-mode",
    label: "SME Mode",
    description: "Expertise métier et adaptation commerciale avancée.",
    category: "Reinforcement",
    mappedModules: ["m25", "m4", "m28"],
    requiredPlan: PlanId.FREE,
    keywords: ["sme", "business", "soncas", "gpl"]
  },
  {
    id: "visual-pipeline",
    label: "Visual Pipeline",
    description: "Gouvernance des flux visuels, manga et storyboard.",
    category: "Integration",
    mappedModules: ["m27"],
    requiredPlan: PlanId.PRO,
    keywords: ["visual", "vg-plus"]
  },
  {
    id: "governance-audit",
    label: "Governance Audit",
    description: "Audit ledger hashable et trace complète des essences.",
    category: "Reinforcement",
    mappedModules: ["m6"],
    requiredPlan: PlanId.FREE,
    keywords: ["audit", "halo", "trace"]
  },
  {
    id: "decision-compression",
    label: "Decision Compression",
    description: "Moteur anti-boucle : compression des incertitudes pour forcer l'action minimale utile.",
    category: "Reinforcement",
    mappedModules: ["m29"],
    requiredPlan: PlanId.FREE,
    keywords: ["decision", "compression", "essence-me"]
  }
];
